export const data = [
    {
      id: '1',
      name: 'Jessica Parker',
      age: 23,
      text: "Hello 😂",
      unread: 4,
      time: 22,
      profession: 'Professional model',
      distance: '1 km',
      image: require('../assets/images/photo.png'),
      activity: require('../assets/images/photo.png'),
    },
    {
      id: '2',
      name: 'Emily Johnson',
      age: 27,
      text: 'I missed your call',
      time: 22,
      profession: 'Graphic Designer',
      distance: '2 km',
      image: require('../assets/images/photo2.png'), // Replace with actual image URL
    },
    {
      id: '3',
      name: 'Sophia Williams',
      age: 22,
      text: 'when will you be seeing me😊',
      time: 10,
      unread: 8,
      profession: 'Software Engineer',
      distance: '1.5 km',
      image: require('../assets/images/photo2.png'), // Replace with actual image URL
      activity: require('../assets/images/photo3.png'),
    },
    {
      id: '4',
      name: 'Olivia Brown',
      age: 25,
      text: 25,
      time: 1,
      profession: 'Marketing Specialist',
      distance: '3 km',
      image: require('../assets/images/onboarding/female1.png'), // Replace with actual image URL
      activity: require('../assets/images/photo4.png'),
    },
    {
      id: '5',
      name: 'Ava Davis',
      age: 24,
      time: 43,
      text: 24,
      profession: 'Photographer',
      distance: '0.5 km',
      image: require('../assets/images/photo3.png'), // Replace with actual image URL
    },
    {
        id: '6',
        name: 'Ava Davis',
        text: 24,
        time: 18,
        age: 24,
        profession: 'Photographer',
        distance: '0.5 km',
      //   unread: 4,
        image: require('../assets/images/photo4.png'), // Replace with actual image URL
      },
      {
        id: '7',
        name: 'Ava Davis',
        text: 24,
        unread: 4,
        time: 43,
        age: 24,
        profession: 'Photographer',
        distance: '0.5 km',
        image: require('../assets/images/onboarding/female1.png'),
        activity: require('../assets/images/photo4.png'), // Replace with actual image URL
      },
      {
        id: '8',
        name: 'Quarms Henry',
        text: 24,
        unread: 4,
        time: 4,
        age: 24,
        profession: 'Photographer',
        distance: '0.5 km',
        image: require('../assets/images/onboarding/female1.png'), // Replace with actual image URL
        activity: require('../assets/images/photo2.png'),
      },
      {
        id: '9',
        name: 'Mary Daniels',
        text: 24,
        unread: 164,
        time: 4,
        age: 24,
        profession: 'Photographer',
        distance: '0.5 km',
        image: require('../assets/images/onboarding/female1.png'), // Replace with actual image URL
        activity: require('../assets/images/photo.png'),
      },
    // Add more users as needed
  ];